github: 'eigenein'
custom:
- 'https://www.paypal.me/eigenein'
- 'https://bunq.me/eigenein'
- 'https://money.yandex.ru/to/410011693851843'
ko_fi: 'eigenein'
open_collective: 'eigenein'
patreon: 'eigenein'
